///ts:export=foo
import A1_file = require('./a/A1'); ///ts:export:generated
export var A1 = A1_file; ///ts:export:generated
import A2_file = require('./a/A2'); ///ts:export:generated
export var A2 = A2_file; ///ts:export:generated
import a_file = require('./a/index'); ///ts:export:generated
export var a = a_file; ///ts:export:generated
import b1_file = require('./b/b1'); ///ts:export:generated
export var b1 = b1_file; ///ts:export:generated
import b2_file = require('./b/b2'); ///ts:export:generated
export var b2 = b2_file; ///ts:export:generated